basic/urls.py
from django.urls import path
from . import views

app_name='basic'

urlpatterns = [
	path('',views.index,name="index"),
	path('register',views.register,name="register"),
]

finityStore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('django.contrib.auth.urls')),
	path('',include("basic.urls")),
	path('',include("store.urls")),
]

store/urls.py
from django.urls import path
from . import views

app_name='store'

urlpatterns = [
	path("itemList",views.ItemList.as_view(),name="Item List"),
	path("product/<int:pk>",views.Product.as_view(),name="Product"),

	path("wishlist",views.Wishlist.as_view(),name="Wishlist"),
	path("addToWishlist/<int:itemId>",views.AddToWishList.as_view(),name="Add to Wishlist"),
	path("removeFromWishlist/<int:wishId>",views.RemoveFromWishList.as_view(),name="Remove From Wishlist"),

	path("cart",views.Cart.as_view(),name="Cart"),
	path("addToCart/<int:productId>",views.AddToCart.as_view(),name="Add to Cart"),

	path("incrementCart/<int:cartId>",views.IncrementCart.as_view(),name="Increment Cart"),
	path("decrementCart/<int:cartId>",views.DecrementCart.as_view(),name="Decrement Cart"),

	path("checkout",views.checkout,name="checkout"),
]

basic/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models

class Item(models.Model):
	RARITY_CHOICES = [
		(0,"Common"),
		(1,"Uncommon"),
		(2,"Rare"),
		(3,"Epic"),
		(4,"Legendary"),
	]
	TYPE_CHOICES = [
		(0,"Helmet"),
		(1,"Chestplate"),
		(2,"Leggings"),
		(3,"Boots"),
		(4,"Sword"),
		(5,"Staff"),
		(6,"Bow"),
	]

	Name = models.CharField(unique=True,max_length=100)
	Description = models.TextField(null=True)
	Details = models.TextField(null=True)
	Rarity = models.PositiveSmallIntegerField(choices=RARITY_CHOICES)
	Type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)
	Image = models.ImageField(upload_to="static/items")


class Listing(models.Model):
	TYPE_CHOICES = [
		(0,"Store"),
		(1,"Auction"),
		(2,"BIN"),
	]
	STATUS_CHOICES = [
		(0,"Available"),
		(1,"Expired"),
		(2,"Purchased"),
	]

	Type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES)
	Status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
	Item = models.ForeignKey(Item,related_name="Listings",null=True,on_delete=models.SET_NULL)
	Price = models.DecimalField(max_digits=9,decimal_places=4)
	Stock = models.PositiveIntegerField()
	Listing = models.DateTimeField()
	Expiration = models.DateTimeField()
	Seller = models.ForeignKey(User,related_name="Listings",null=True,on_delete=models.SET_NULL)
	Buyer = models.ForeignKey(User,related_name="Purchases",null=True,on_delete=models.SET_NULL)


class Bid(models.Model):
	Listing = models.ForeignKey(Listing,related_name="Bids",null=True,on_delete=models.SET_NULL)
	Bidder = models.ForeignKey(User,related_name="Bids",null=True,on_delete=models.SET_NULL)
	Price = models.DecimalField(max_digits=9,decimal_places=4)
	Time = models.DateTimeField()


class Wishlist(models.Model):
	User = models.ForeignKey(User,related_name="Wishlist",on_delete=models.CASCADE)
	Item = models.ForeignKey(Item,related_name="wishlist",on_delete=models.CASCADE)
	Created = models.DateTimeField(auto_now_add=True)

class Cart(models.Model):
	User = models.ForeignKey(User,related_name="Cart",on_delete=models.CASCADE)
	Listing = models.ForeignKey(Listing,related_name="Cart",on_delete=models.CASCADE)
	Quantity = models.PositiveIntegerField()

basic/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpRequest,HttpResponse
from django.shortcuts import render,redirect

def index(request:HttpRequest):
	return render(request,"index.html",{})

def register(request:HttpRequest):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect("login")
	else:
		form = UserCreationForm()
	return render(request,"registration/register.html",{"form":form})

store/views.py
from collections.abc import Sequence
from typing import Any
from django.db.models.query import QuerySet

from django.http import HttpRequest,HttpResponse,Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.views.generic import DetailView,ListView,DeleteView,CreateView,View
from . import models


class ItemList(ListView):
	model = models.Listing
	ordering = None
	paginate_by = 50
	template_name = 'store/itemList.html'
	context_object_name = 'products'
	
	def get_queryset(self) -> QuerySet[Any]:
		now = timezone.now()

		querySet = self.model.objects.filter(
			Status=0,
			Item__isnull=False,
			Stock__gt=0,
			# Item__Type__in=self.request.GET.getlist("type"),
			# Item__Rarity__in=self.request.GET.getlist("rarity"),
			# Type=self.request.GET.get("listing"),
			# Expiration__gt=now 
		)

		ordering = self.get_ordering()
		if ordering:
			if isinstance(ordering, str):
				ordering = (ordering,)
			queryset = queryset.order_by(*ordering)
		
		return querySet
	
	def get_ordering(self) -> Sequence[str]:
		if "low" in self.request.GET:
			return ["Price",]
		if "high" in self.request.GET:
			return ["-Price",]
		if "new" in self.request.GET:
			return ["-Listing",]
		if "ending" in self.request.GET:
			return ["Expiration",]
		if "lowrarity" in self.request.GET:
			return ["Item__Rarity",]
		if "highrarity" in self.request.GET:
			return ["-Item__Rarity",]
		return []

class Product(DetailView):
	model=models.Listing
	template_name='store/product.html'
	context_object_name='product'

def cart(request:HttpRequest):
	return render(request,"store/cart.html",{})

class Wishlist(ListView):
	model=models.Wishlist
	template_name='store/wishlist.html'
	context_object_name='wishlist'

	def get_queryset(self) -> QuerySet[Any]:
		querySet = self.model.objects.filter(User=self.request.user)

		ordering = self.get_ordering()
		if ordering:
			if isinstance(ordering, str):
				ordering = (ordering,)
			queryset = queryset.order_by(*ordering)
		return querySet

class AddToWishList(View):
	def post(self,request:HttpRequest,itemId):
		wish,created = models.Wishlist.objects.get_or_create(
			User=request.user,
			Item=get_object_or_404(models.Item,id= itemId),
		)
		if created:
			return HttpResponse("Added to Wishlist")
		return HttpResponse("Already in Wishlist")

class RemoveFromWishList(View):
	def post(self,request:HttpRequest,wishId):
		wish = get_object_or_404(models.Wishlist,id=wishId)
		wish.delete()
		return redirect("store:Wishlist")


class Cart(ListView):
	model=models.Cart
	template_name='store/cart.html'
	context_object_name='carts'

	def get_queryset(self) -> QuerySet[Any]:
		querySet = self.model.objects.filter(User=self.request.user)

		ordering = self.get_ordering()
		if ordering:
			if isinstance(ordering, str):
				ordering = (ordering,)
			queryset = queryset.order_by(*ordering)
		return querySet
	
	def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
		response_kwargs.setdefault("content_type", self.content_type)
		context['totalPrice'] = sum(cart.Listing.Price * cart.Quantity for cart in context.get(self.context_object_name))
		return self.response_class(
			request=self.request,
			template=self.get_template_names(),
			context=context,
			using=self.template_engine,
			**response_kwargs,
		)

class AddToCart(View):
	def post(self,request:HttpRequest,productId):
		cart,created = models.Cart.objects.get_or_create(
			User=request.user,
			Listing=get_object_or_404(models.Listing,id=productId),
			Quantity=request.POST.get("quantity"),
		)
		if created:
			return HttpResponse("Added to Cart")
		return HttpResponse("Already in Cart")
	
class IncrementCart(View):
	def post(self,request:HttpRequest,cartId):
		cart = get_object_or_404(models.Cart,id=cartId)
		cart.Quantity +=1
		if cart.Quantity <= cart.Listing.Stock:
			cart.save()
		return HttpResponse(cart.Quantity)

class DecrementCart(View):
	def post(self,request:HttpRequest,cartId):
		cart = get_object_or_404(models.Cart,id=cartId)
		cart.Quantity -=1
		if cart.Quantity<1:
			cart.delete()
		else:
			cart.save()
		return HttpResponse(cart.Quantity)

def checkout(request:HttpRequest):
	return HttpResponse("Working on it!")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>{% block title %} Insert Title {% endblock %}</title>
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
	<link rel="stylesheet" href="{% static 'output.css' %}">
	{% block head %} {% endblock %}
</head>
<body>
	<div class="flex flex-col min-h-screen max-h-screen">
		<div class="w-full">{% block top %}{% endblock %}</div>
		
		<div class="flex w-full justify-between flex-grow overflow-hidden">
				<div class="overflow-y-auto max-h-full">{% block left %}{% endblock %}</div>
				<div class="flex-1 overflow-y-auto max-h-full">{% block middle %}{% endblock %}</div>
				<div class="overflow-y-auto max-h-full">{% block right %}{% endblock %}</div> 
		</div>
	</div>
	
	<div class="w-full p-2 md:p-4 lg:p-6 empty:p-0">{% block bottom %}{% endblock %}</div>

	{% block foot %}{% endblock %}
</body>

<script src="{% static 'js/htmx.min.js' %}"></script> 

</html>

templates/components/footer.html
<h1>Footer</h1>

templates/components/hero.html
{% load static %}

<div class="hero h-1/2 md:h-3/4 gap-4 md:gap-6 lg:gap-8">
	<h1>This is it!</h1>
	<p class="mx-10 sm:mx-20 md:mx-40 lg:mx-60">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum et odio, fuga quo ipsum voluptates sapiente assumenda dolorum quasi distinctio tempora omnis nisi consequatur totam in unde consectetur culpa modi!</p>
	<form class="w-5/6 md:w-1/2">
		<input type="text" name="search" id="search" class="w-3/4 p-1.5">
		<button class="w-1/6 md:1/6 py-1.5">Search</button>
	</form>
</div>

templates/components/main.html
{% load static %}

<div class="main p-2 md:p-4 lg:p-8">
	
	<header class="py-6">
		<h2>Featured</h2>
		<div class="featured gap-6 p-8" id="items">
      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 1 %}">
				<img src="{% static 'img/sword1.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 2 %}">
				<img src="{% static 'img/sword2.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 3 %}">
				<img src="{% static 'img/sword3.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>
    </div>
	</header>
	<main class="py-6">
		<h2>Newest</h2>
		<div class="newest gap-6 p-8" id="items">
      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 1 %}">
				<img src="{% static 'img/sword1.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 2 %}">
				<img src="{% static 'img/sword2.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 3 %}">
				<img src="{% static 'img/sword3.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>
    </div>
	</main>
	<footer class="py-6">
		<h2>Ending Soon</h2>
		<div class="ending gap-6 p-8" id="items">
      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 1 %}">
				<img src="{% static 'img/sword1.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 2 %}">
				<img src="{% static 'img/sword2.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group p-2 md:p-4 lg:p-8" href="{% url 'store:Product' 3 %}">
				<img src="{% static 'img/sword3.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>
    </div>
	</footer>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %} Index {% endblock %}

{% block top %}
{% include 'nav.html' with page="index" %}
{% endblock %}

{% block left %}{% endblock %}

{% block middle %}
{% include 'components/hero.html'%}
{% include 'components/main.html'%}
{% endblock %}


{% block right %}{% endblock %}


{% block bottom %}
{% include 'components/footer.html'%}
{% endblock %}

templates/nav.html
{% load static %}
<nav class="navbar h-16 mx-auto px-2 sm:px-6 lg:px-8">
		<div class="first space-x-4">
			<img class="h-8 w-auto rounded-lg" src="{% static 'img/logo.jpeg' %}" alt="Your Company">
			
			<a href="{% url 'basic:index' %}" {% if page == "index" %} class="navItemSelected" aria-current="page" {% else %} class = "navItem" {% endif %}>Home</a>
			<a href="{% url 'store:Item List' %}" {% if page == "itemlist" %} class="navItemSelected" aria-current="page" {% else %} class = "navItem" {% endif %}>Items</a>
			<a href="{% url 'store:Wishlist' %}" {% if page == "wishlist" %} class="navItemSelected" aria-current="page" {% else %} class = "navItem" {% endif %}>WishList</a>
			<a href="{% url 'store:Cart' %}" {% if page == "cart" %} class="navItemSelected" aria-current="page" {% else %} class = "navItem" {% endif %}>Cart</a>
		</div>
		<div class="last">
			<a href="/profile">
				<img class="h-8 w-8 rounded-full" src="{% static 'img/profile.jpeg' %}" alt="">
			</a>
		</div>
</nav>

templates/store/cart.html
{% extends 'base.html' %}
{% block title %} Cart {% endblock %}

{% block top %}
{% include 'nav.html' with page="cart" %}
{% endblock %}

{% load static %}

{% block middle %}
<div class="cartItems p-2 md:p-4 lg:p-8 min-h-full">
	<h2 class="mb-10">Cart Items</h2>
	<div class="items gap-4">
		{% for cart in carts %}
		<div class="item p-2 md:p-4 lg:p-8 gap-4 md:w-3/4">
			<img alt="product-image" class="lg:w-1/4"  src="{{cart.Listing.Item.Image.url}}"/>
			<div class="infoBox">
				<div class="info">
					<h3>{{cart.Listing.Item.Name}}</h3>
					<h4>Price: ${{cart.Listing.Price}}</h4>
					<h4>Type: {{cart.Listing.Item.get_Type_display}}</h4>
					<h4>Rarity: {{cart.Listing.Item.get_Rarity_display}}</h4>
					<p>{{cart.Listing.Item.Description|slice:":100"}}{% if cart.Listing.Item.Description|length > 100 %}...{% endif %}</p>
				</div>
				
				<div class="count">
					<span class="left" hx-post="{% url 'store:Decrement Cart' cart.id %}" hx-trigger="click" hx-target="#quantity-{{ cart.id }}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'> - </span>
					<p id="quantity-{{ cart.id }}" class="px-2">{{cart.Quantity}}</p>
					<span class="right" hx-post="{% url 'store:Increment Cart' cart.id %}" hx-trigger="click" hx-target="#quantity-{{ cart.id }}" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'> + </span>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block right %}
<div class="cartList p-2 md:p-4 lg:p-8 min-h-full">
	<h2>Cart List</h2>
	<div class="list gap-4 py-4 border-b-2">
		<h4>Item</h4>
		<h4>Quantity</h4>
		<h4>Price</h4>
		{% for cart in carts %}
			<p>{{cart.Listing.Item.Name}}</p>
			<p>{{cart.Quantity}}</p>
			<p>${{cart.Listing.Price}}</p>
		{% endfor %}
	</div>

	<div class="list gap-4 py-4 border-b-2">
		<h4>Total:</h4>
		<h4>${{totalPrice}} USD</h4>
	</div>
	<button class="mt-6 w-full py-1.5">Check out</button>
</div>
{% endblock %}

{% block foot %}
<script>
	document.body.addEventListener('htmx:afterRequest', function(event) {
			// Reload the page after the HTMX request is complete
			window.location.reload();
	});
</script>
{% endblock %}

templates/store/components/items.html
{% load static %}
<div class="itemList p-4 md:p-8 lg:p-12 min-h-full">
    <h2 class="pb-8">Results</h2>

    <div class="itemGrid relative" id="items">

      <a class="group" href="{% url 'store:Product' 1 %}">
				<img src="{% static 'img/sword1.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group" href="{% url 'store:Product' 2 %}">
				<img src="{% static 'img/sword2.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group" href="{% url 'store:Product' 3 %}">
				<img src="{% static 'img/sword3.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group" href="{% url 'store:Product' 3 %}">
				<img src="{% static 'img/sword4.jpeg' %}">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group" href="{% url 'store:Product' 4 %}">
				<img src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>

      <a class="group" href="{% url 'store:Product' 5 %}">
				<img src="https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg">
        <div class="item mt-4">
					<h3>Basic Tee</h3>
          <p>$35</p>
        </div>
      </a>
			{% for product in products %}
				<a class="group" href="{% url 'store:Product' product.id %}">
					<img src="{{product.Item.Image.url}}">
					<div class="item mt-4">
						<h3>{{product.Item.Name}}</h3>
						<p>${{product.Price}}</p>
					</div>
				</a>
			{% empty %}
				<h3>No Items</h3>
			{% endfor %}
    </div>
</div>

templates/store/itemList.html
{% extends 'base.html' %}

{% block title %} Item List {% endblock %}

{% block top %}
{% include 'nav.html' with page="itemlist" %}
{% endblock %}

{% block left %}
{% include 'store/components/filter.html' %}
{% endblock %}

{% block middle %}
{% include 'store/components/items.html' %}
{% endblock %}

templates/store/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Product {% endblock %}

{% block top %}
{% include 'nav.html' with page="none" %}
{% endblock %}

{% block middle %}
<div class="product px-4 md:px-8 lg:px-12">
	<img src="{% static 'img/sword1.jpeg' %}" class="p-4 md:p-8 lg:p-12">

	<div class="py-4 md:py-8 lg:py-12">
		<h2 class="py-2">{{product.Item.Name}}</h2>
		<h3>Price/Current Bid : ${{product.Price}}</h3>
		<h4>Ends: {{product.Expiration}}</h4>
		<h4>Type: {{product.Item.get_Type_display}}</h4>
		<h4>Rarity: {{product.Item.get_Rarity_display}}</h4>
		<h4>Quantity: {{product.Stock}}</h4>
		<p class="py-2">{{product.Item.Desciption}}</p>
		
		{% if product.Type == 1 %}
			<form class="space-y-4 py-3" method="post">
				{% csrf_token %}
				<label for="bid">Place Bid</label>
				<input type="number" name="bid" min="193" id="bid" value="193">
				<button type="submit" name="bid" value="bid">Bid</button>
				<button hx-post="{% url 'store:Add to Wishlist' product.Item.id %}" hx-trigger="click" >Add to wishlist</button>
			</form>
		{% else %}
			<form class="space-y-4 py-3" method="post">
				{% csrf_token %}
				
				<label for="quantity">Quantity</label>
				<input type="number" min="1" id="quantity" name="quantity" value="1">
			
				<div class="flex space-x-6">
					<button type="submit" name="action" value="buy">Buy</button>
					<button hx-post="{% url 'store:Add to Cart' product.id %}" hx-trigger="click"  >Add to Cart</button>
					<button hx-post="{% url 'store:Add to Wishlist' product.Item.id %}" hx-trigger="click" >Add to wishlist</button>
				</div>
			</form>
		{% endif %}
		
	</div>

	<div class="p-4 md:p-8 lg:p-12 lg:col-span-2">
		<h3 class="text-3xl tracking-tight text-gray-900">Details</h3>
		<p class="text-gray-900 py-6">{{product.Item.Details}}</p>
	</div>
</div>

{% endblock %}

templates/store/wishlist.html
{% extends 'base.html' %}

{% block title %} Wishlist {% endblock %}

{% block top %}
{% include 'nav.html' with page="wishlist" %}
{% endblock %}

{% load static %}

{% block middle %}
<div class="wishList p-2 md:p-4 lg:p-8 min-h-full">
	<h2 class="mb-10">Wish List</h2>
	<div class="items gap-4">
		{% for wish in wishlist %}
			<div class="item p-2 md:p-4 lg:p-8 gap-4 md:w-3/4">
				<img alt="product-image" class="lg:w-1/4"  src="{{wish.Item.Image.url}}"/>
				<div class="infoBox">
					<div class="info">
						<h3>{{wish.Item.Name}}</h3>
						<h4>Type: {{wish.Item.get_Type_display}}</h4>
						<h4>Rarity: {{wish.Item.get_Rarity_display}}</h4>
						<p>{{wish.Item.Description|slice:":100"}}{% if wish.Item.Description|length > 100 %}...{% endif %}</p>
					</div>
					<form class="control" method="post" action="{% url 'store:Remove From Wishlist' wish.id %}">
						{% csrf_token %}
						<button class="remove p-2"> Remove </button>
					</form>
				</div>
			</div>
		{% endfor %}
	</div>
</div>
{% endblock %}